version: 2.1
orbs:
  node: circleci/node@5.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  install_build_and_test:
    executor: node/default
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm install
      - run:
          command: npm run test
          name: Run tests
      - store_test_results:
          path: test-results

  awsEb_setup:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
workflows:
  test_and_deploy:
      jobs:
        - install_build_and_test
        - awsEb_setup
        - hold:
            type: approval
            requires:
              - install_build_and_test
              - awsEb_setup
        - eb/deploy:
            application-name: Playlist_Wizard
            environment-name: Playlistwizard-env
            requires:
              - hold
            filters:
              branches:
                only: main # only deploy when on main
