version: 2.1
orbs:
  node: circleci/node@5.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  install_build_and_test:
    executor: node/default
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm install
      - run:
          command: npm run build
          name: Run build
      - persist_to_workspace:
          root: /
          paths:
            - build
      - run:
          command: npm run test
          name: Run tests
      - store_test_results:
          path: test-results

  awsEb_deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - attach_workspace:
          at: /
      - eb/setup
      - run:
          command: |
            eb init Playlist_Wizard -r $AWS_DEFAULT_REGION -p node.js
            eb deploy Playlistwizard-env
            eb status
          name: AWS EB setup and deploy
workflows:
  test_and_deploy:
      jobs:
        - install_build_and_test
        - hold:
            type: approval
            requires:
              - install_build_and_test
        - AWSEB_deploy:
            requires:
              - hold
            filters:
              branches:
                only: main # only deploy when on main
